version: "3.8"
services: 
  backend:
    build: ./server
    ports:
      - 5000:5000
    env_file: ./server/.env
    volumes:
      - track-ent-data:/data
  bot:
    build: ./bot
    env_file: ./bot/.env
    ports: 
      - 4000:4000
  cron:
    build: ./cron
    env_file: ./cron/.env
    depends_on: 
      - backend
  front:
    build: ./client
    ports: 
      - 3000:3000
    env_file: ./client/.env
volumes:
  track-ent-data:
    name: track-ent-data